// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trades.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Trades_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Trades_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Trades_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Trades_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Trades_2eproto;
class TradeInfo;
class TradeInfoDefaultTypeInternal;
extern TradeInfoDefaultTypeInternal _TradeInfo_default_instance_;
class Trades;
class TradesDefaultTypeInternal;
extern TradesDefaultTypeInternal _Trades_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::TradeInfo* Arena::CreateMaybeMessage<::TradeInfo>(Arena*);
template<> ::Trades* Arena::CreateMaybeMessage<::Trades>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class TradeInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TradeInfo) */ {
 public:
  TradeInfo();
  virtual ~TradeInfo();

  TradeInfo(const TradeInfo& from);
  TradeInfo(TradeInfo&& from) noexcept
    : TradeInfo() {
    *this = ::std::move(from);
  }

  inline TradeInfo& operator=(const TradeInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline TradeInfo& operator=(TradeInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TradeInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TradeInfo* internal_default_instance() {
    return reinterpret_cast<const TradeInfo*>(
               &_TradeInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TradeInfo& a, TradeInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(TradeInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TradeInfo* New() const final {
    return CreateMaybeMessage<TradeInfo>(nullptr);
  }

  TradeInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TradeInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TradeInfo& from);
  void MergeFrom(const TradeInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TradeInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TradeInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Trades_2eproto);
    return ::descriptor_table_Trades_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPriceFieldNumber = 1,
    kQuantityFieldNumber = 2,
    kBidOrderIdFieldNumber = 3,
    kAskOrderIdFieldNumber = 4,
  };
  // double price = 1;
  void clear_price();
  double price() const;
  void set_price(double value);
  private:
  double _internal_price() const;
  void _internal_set_price(double value);
  public:

  // uint64 quantity = 2;
  void clear_quantity();
  ::PROTOBUF_NAMESPACE_ID::uint64 quantity() const;
  void set_quantity(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_quantity() const;
  void _internal_set_quantity(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 bidOrderId = 3;
  void clear_bidorderid();
  ::PROTOBUF_NAMESPACE_ID::uint64 bidorderid() const;
  void set_bidorderid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_bidorderid() const;
  void _internal_set_bidorderid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 askOrderId = 4;
  void clear_askorderid();
  ::PROTOBUF_NAMESPACE_ID::uint64 askorderid() const;
  void set_askorderid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_askorderid() const;
  void _internal_set_askorderid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:TradeInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  double price_;
  ::PROTOBUF_NAMESPACE_ID::uint64 quantity_;
  ::PROTOBUF_NAMESPACE_ID::uint64 bidorderid_;
  ::PROTOBUF_NAMESPACE_ID::uint64 askorderid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Trades_2eproto;
};
// -------------------------------------------------------------------

class Trades :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Trades) */ {
 public:
  Trades();
  virtual ~Trades();

  Trades(const Trades& from);
  Trades(Trades&& from) noexcept
    : Trades() {
    *this = ::std::move(from);
  }

  inline Trades& operator=(const Trades& from) {
    CopyFrom(from);
    return *this;
  }
  inline Trades& operator=(Trades&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Trades& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Trades* internal_default_instance() {
    return reinterpret_cast<const Trades*>(
               &_Trades_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Trades& a, Trades& b) {
    a.Swap(&b);
  }
  inline void Swap(Trades* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Trades* New() const final {
    return CreateMaybeMessage<Trades>(nullptr);
  }

  Trades* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Trades>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Trades& from);
  void MergeFrom(const Trades& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Trades* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Trades";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Trades_2eproto);
    return ::descriptor_table_Trades_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTradesFieldNumber = 1,
  };
  // repeated .TradeInfo trades = 1;
  int trades_size() const;
  private:
  int _internal_trades_size() const;
  public:
  void clear_trades();
  ::TradeInfo* mutable_trades(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TradeInfo >*
      mutable_trades();
  private:
  const ::TradeInfo& _internal_trades(int index) const;
  ::TradeInfo* _internal_add_trades();
  public:
  const ::TradeInfo& trades(int index) const;
  ::TradeInfo* add_trades();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TradeInfo >&
      trades() const;

  // @@protoc_insertion_point(class_scope:Trades)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TradeInfo > trades_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Trades_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TradeInfo

// double price = 1;
inline void TradeInfo::clear_price() {
  price_ = 0;
}
inline double TradeInfo::_internal_price() const {
  return price_;
}
inline double TradeInfo::price() const {
  // @@protoc_insertion_point(field_get:TradeInfo.price)
  return _internal_price();
}
inline void TradeInfo::_internal_set_price(double value) {
  
  price_ = value;
}
inline void TradeInfo::set_price(double value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:TradeInfo.price)
}

// uint64 quantity = 2;
inline void TradeInfo::clear_quantity() {
  quantity_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TradeInfo::_internal_quantity() const {
  return quantity_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TradeInfo::quantity() const {
  // @@protoc_insertion_point(field_get:TradeInfo.quantity)
  return _internal_quantity();
}
inline void TradeInfo::_internal_set_quantity(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  quantity_ = value;
}
inline void TradeInfo::set_quantity(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_quantity(value);
  // @@protoc_insertion_point(field_set:TradeInfo.quantity)
}

// uint64 bidOrderId = 3;
inline void TradeInfo::clear_bidorderid() {
  bidorderid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TradeInfo::_internal_bidorderid() const {
  return bidorderid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TradeInfo::bidorderid() const {
  // @@protoc_insertion_point(field_get:TradeInfo.bidOrderId)
  return _internal_bidorderid();
}
inline void TradeInfo::_internal_set_bidorderid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  bidorderid_ = value;
}
inline void TradeInfo::set_bidorderid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_bidorderid(value);
  // @@protoc_insertion_point(field_set:TradeInfo.bidOrderId)
}

// uint64 askOrderId = 4;
inline void TradeInfo::clear_askorderid() {
  askorderid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TradeInfo::_internal_askorderid() const {
  return askorderid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TradeInfo::askorderid() const {
  // @@protoc_insertion_point(field_get:TradeInfo.askOrderId)
  return _internal_askorderid();
}
inline void TradeInfo::_internal_set_askorderid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  askorderid_ = value;
}
inline void TradeInfo::set_askorderid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_askorderid(value);
  // @@protoc_insertion_point(field_set:TradeInfo.askOrderId)
}

// -------------------------------------------------------------------

// Trades

// repeated .TradeInfo trades = 1;
inline int Trades::_internal_trades_size() const {
  return trades_.size();
}
inline int Trades::trades_size() const {
  return _internal_trades_size();
}
inline void Trades::clear_trades() {
  trades_.Clear();
}
inline ::TradeInfo* Trades::mutable_trades(int index) {
  // @@protoc_insertion_point(field_mutable:Trades.trades)
  return trades_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TradeInfo >*
Trades::mutable_trades() {
  // @@protoc_insertion_point(field_mutable_list:Trades.trades)
  return &trades_;
}
inline const ::TradeInfo& Trades::_internal_trades(int index) const {
  return trades_.Get(index);
}
inline const ::TradeInfo& Trades::trades(int index) const {
  // @@protoc_insertion_point(field_get:Trades.trades)
  return _internal_trades(index);
}
inline ::TradeInfo* Trades::_internal_add_trades() {
  return trades_.Add();
}
inline ::TradeInfo* Trades::add_trades() {
  // @@protoc_insertion_point(field_add:Trades.trades)
  return _internal_add_trades();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TradeInfo >&
Trades::trades() const {
  // @@protoc_insertion_point(field_list:Trades.trades)
  return trades_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Trades_2eproto
